version: "3.1"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: resgistro
      POSTGRES_PASSWORD: registro
      PGDATA: /data/postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "54322:80"
    depends_on:
      - postgres
volumes:
  cache:
    driver: local