FROM node:21

# Set the working directory to /app/api
WORKDIR ./

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
# RUN npm install

# Copy the rest of your application's source code to the container
COPY . .

# Expose a port (if your application uses one)
# EXPOSE 3000

# Start your application
CMD ["npm", "nest", "start"]